### ISSUE TITLE
Network port is not bound to localhost

### ISSUE THREAD

**Issue by sebastianw** [suan/vim-instant-markdown#79]
The script opens a network port (8090) that is not bound to localhost. This means that everyone can access the open file at port 8090 which is a potential privacy/security issue.

**Comment by hsojekok** [comment]
The same issue still exists. The problem lies in a discrepancy between the instant-markdown-d package uploaded and available from the npm repository and the one referenced on github.

My manual fix included the following steps:

1. Run installation as instructed: `[sudo] npm -g install instant-markdown-d`
1. Copy all code from [instant-markdown-d github repository](https://github.com/suan/instant-markdown-d/blob/master/instant-markdown-d)
1. Edit installed npm package: `npm edit instant-markdown-d` or `vi /usr/local/lib/node_modules/instant-markdown-d/instant-markdown-d` _**note:** This was the path on my box and should work everywhere but Windows -- who will need to find the install location themselves_
1. Replace entire 103 lines with 174 lines copied from github repo.
1. Now works as expected.

The first tip-off of the issue were the code differences between both repositories. Perhaps the github repo should be pushed to the npm repo.

**Comment by ashwinvis** [comment]
New versions are out.
